from device import *
out={}
def run(k,js):
 v=ev('(async()=>{const A=__ATTENTION_INBOX__;await A.ready();'+js+'})()');out[k]=v;save('extended.json',out);print(k,json.dumps(v,ensure_ascii=False),flush=True);return v
run('title-only-edit',"const it=A.state.items.find(x=>x.status==='waiting');A.openEditItem(it.id);const before={trigger:it.triggerAt,form:document.querySelector('#capTrigger').value};document.querySelector('#capText').value='实机验证保留原时间';document.querySelector('#capText').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#btnSaveItem').click();await new Promise(r=>setTimeout(r,1500));return {before,after:A.state.items.find(x=>x.id===it.id).triggerAt};")
run('fuzzy-capture',"A.openCapture();document.querySelector('#capText').value='以后看看实机验证阅读资料';document.querySelector('#btnSaveItem').click();await new Promise(r=>setTimeout(r,900));return A.state.items.find(x=>x.title.includes('阅读资料'));")
run('review-retain',"A.openReviewSession();const before=A.needsReviewItems().map(x=>x.id);A.reviewKeepCurrent();A.closeAllSheets();await A.saveAsync();return {before,after:A.needsReviewItems().map(x=>x.id)};")
run('search',"document.querySelector('#btnSearch').click();const x=document.querySelector('#searchInput');x.value='实机验证';x.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(r=>setTimeout(r,400));const result=document.querySelector('#searchResults').innerText;A.closeAllSheets();return result;")
run('recurrence',"const id='verify-repeat-'+Date.now();const it=A.makeItem({id,title:'实机验证周期',triggerAt:Date.now()+86400000,repeat:{every:'day',mode:'calendar'},status:'waiting',priority:'normal'});A.state.items.push(it);await A.saveAsync();await A.completeItem(id);await A.saveAsync();return A.state.items.filter(x=>x.id===id||x.repeatParentId===id||x.title==='实机验证周期').map(x=>({id:x.id,status:x.status,triggerAt:x.triggerAt,repeat:x.repeat,seriesId:x.seriesId}));")
run('restore-no-reminder',"const it=A.state.items.find(x=>x.title==='实机验证已编辑');await A.restoreItem(it.id);A.closeAllSheets();await A.saveAsync();return {status:it.status,triggerAt:it.triggerAt,deadlinePaused:it.deadlinePaused};")
run('parse-matrix',"return ['两小时后实机验证','明天15点实机验证','9月30日截止，提前5天提醒实机验证','每周五下午3点实机验证','以后看看实机验证'].map(text=>({text,parsed:A.parseChineseTime(text,new Date())}));")
run('native-permissions',"return {notification:await Capacitor.Plugins.LocalNotifications.checkPermissions(),exact:await Capacitor.Plugins.LocalNotifications.checkExactNotificationSetting(),pending:await Capacitor.Plugins.LocalNotifications.getPending()};")
